-- 12장
SELECT LPAD(ENAME, LEVEL*4, '*') AS ENAME
  FROM EMP
CONNECT BY PRIOR EMPNO = MGR
START WITH EMPNO = 7839;

SELECT LPAD(ENAME, LEVEL*4, '*') AS ENAME
  FROM EMP
CONNECT BY EMPNO =PRIOR MGR
START WITH EMPNO = 7839;

SELECT LPAD(ENAME, LEVEL*5, '-') AS ENAME
  FROM EMP
CONNECT BY PRIOR EMPNO = PRIOR MGR
START WITH EMPNO = 7369;

SELECT EMPNO AS EMPNO
     , ENAME AS ENAME
     , JOB AS JOB
     , MGR AS MGR
     , PRIOR ENAME AS MGR_NAME
     , LEVEL
     , LPAD(' ',(LEVEL-1)*2,' ') || ENAME AS DEPTH_ENAME
     , SYS_CONNECT_BY_PATH(ENAME,'-')     AS ENMAE_LIST
  FROM EMP
START WITH MGR IS NULL
CONNECT BY PRIOR EMPNO = MGR
ORDER SIBLINGS BY EMPNO;

--쿼리1
SELECT EMPNO AS EMPNO
     , JOB  AS JOB
     , MGR  AS MGR
     , LEVEL AS LV
     , LPAD(' ',(LEVEL-1)*2,' ') || ENAME AS DEPTH_ENAME
     , SYS_CONNECT_BY_PATH(ENAME,'-')     AS ENMAE_LIST
  FROM EMP
START WITH MGR IS NULL
CONNECT BY PRIOR EMPNO = MGR
             AND ENAME <> 'JONES'
ORDER SIBLINGS BY EMPNO;

--쿼리2
SELECT EMPNO AS EMPNO
     , JOB AS JOB
     , MGR AS MGR
     , LEVEL AS LV
     , LPAD(' ',(LEVEL-1)*2,' ') || ENAME AS DEPTH_ENAME
     , SYS_CONNECT_BY_PATH(ENAME,'-')     AS ENMAE_LIST
  FROM EMP
WHERE ENAME <> 'JONES'
START WITH MGR IS NULL
CONNECT BY PRIOR EMPNO = MGR
ORDER SIBLINGS BY EMPNO;

SELECT LPAD(' ',LEVEL*5,'*') AS ENAME
     , SYS_CONNECT_BY_PATH(ENAME,'->') AS "ORDER(LOW -> HIGH)"
  FROM EMP
START WITH EMPNO=7369
CONNECT BY EMPNO = PRIOR MGR;

SELECT LPAD(' ',LEVEL*5,'*') AS ENAME
     , SYS_CONNECT_BY_PATH(ENAME,'->') AS "ORDER(LOW -> HIGH)"
  FROM EMP
WHERE CONNECT_BY_ISLEAF = 0
START WITH EMPNO=7369
CONNECT BY EMPNO = PRIOR MGR;

SELECT LPAD(' ',LEVEL*5,'*') AS ENAME
     , SYS_CONNECT_BY_PATH(ENAME,'->') AS "ORDER(LOW -> HIGH)"
  FROM EMP
WHERE CONNECT_BY_ISLEAF = 1
START WITH EMPNO=7369
CONNECT BY EMPNO = PRIOR MGR;

SELECT EMPNO AS EMPNO
     , ENAME AS ENAME
     , CONNECT_BY_ROOT EMPNO AS "ROOT EMPNO"
     , SYS_CONNECT_BY_PATH(ENAME,'<-') AS "ROOT <- LEAF"
  FROM EMP
WHERE LEVEL > 1
START WITH EMPNO=7369
CONNECT BY EMPNO = PRIOR MGR;

SELECT EMPNO AS EMPNO
     , ENAME AS ENAME
     , CONNECT_BY_ROOT EMPNO AS "ROOT EMPNO"
     , SYS_CONNECT_BY_PATH(ENAME,'<-') AS "ROOT <- LEAF"
  FROM EMP
WHERE LEVEL = 1
START WITH EMPNO=7369
CONNECT BY EMPNO = PRIOR MGR;

SELECT EMPNO AS EMPNO
     , ENAME AS ENAME
     , CONNECT_BY_ROOT EMPNO AS "ROOT EMPNO"
     , SYS_CONNECT_BY_PATH(ENAME,'<-') AS "ROOT <- LEAF"
  FROM EMP
WHERE LEVEL = 2
START WITH EMPNO=7369
CONNECT BY EMPNO = PRIOR MGR;

SELECT EMPNO AS EMPNO
     , ENAME AS ENAME
     , CONNECT_BY_ROOT EMPNO AS "ROOT EMPNO"
     , SYS_CONNECT_BY_PATH(ENAME,'<-') AS"ROOT <- LEAF"
  FROM EMP
WHERE LEVEL = 3
START WITH EMPNO=7369
CONNECT BY EMPNO = PRIOR MGR;

------------------------ 연습문제 ------------------------------

-- 1번
SELECT LPAD(E.NAME||'-'||D.DNAME||'-'||NVL(E.POSITION,'TEAM-WORKER'), LEVEL*27, '-') "NAME AND POSITION"
FROM EMP2 E, (SELECT DNAME, DCODE, PDEPT
                  FROM DEPT2) D
WHERE E.DEPTNO = D.DCODE
CONNECT BY PRIOR E.EMPNO = E.PEMPNO
START WITH EMPNO = '19900101'
ORDER SIBLINGS BY E.NAME;

-- 2번
SELECT LPAD(E.NAME||'-'||D.DNAME||'-'||NVL(E.POSITION, 'TEAM-WORKER'), LEVEL*48, '-') "NAME AND POSITION"
FROM EMP2 E, (SELECT DNAME, DCODE, PDEPT
                FROM DEPT2) D
WHERE     E.DEPTNO = D.DCODE
CONNECT BY PRIOR E.EMPNO = E.PEMPNO
START WITH EMPNO = '19966102' ;

-- 3번
SELECT LPAD(E.NAME||'-'||D.DNAME||'-'||NVL(E.POSITION, 'TEAM-WORKER'), LEVEL*37, '-') "NAME AND POSITION"
FROM EMP2 E, (
       SELECT  DNAME, DCODE, PDEPT
       FROM    DEPT2
       ) D
WHERE E.DEPTNO = D.DCODE
CONNECT BY E.EMPNO = PRIOR E.PEMPNO
START WITH empno = '20000334'
;

-- 4번
SELECT NAME, PRIOR NAME MGR_NAME
FROM EMP2
START WITH pempno IS NULL
CONNECT BY PRIOR EMPNO = PEMPNO ;

-- 5번
SELECT E.EMPNO
     , (E.NAME||' '||D.DNAME||' '||NVL(E.POSITION, 'TEAM-WORKER')) "ENAME AND POSITION"
     ,(SELECT  COUNT(*)
         FROM    EMP2
       START WITH EMPNO = E.EMPNO
       CONNECT BY PRIOR EMPNO = PEMPNO) -1 COUNT
FROM    EMP2 E, (
                  SELECT  DNAME, DCODE
                  FROM    DEPT2
                 ) D
WHERE  E.DEPTNO = D.DCODE
ORDER BY 3 DESC ;

-- 6번
SELECT LPAD(E.NAME||'-'||D.DNAME||'-'||NVL(E.POSITION, 'TEAM-WORKER'), LEVEL*37, '-') "NAME AND POSITION"
FROM EMP2 E, (
      SELECT  DNAME, DCODE, PDEPT
      FROM    DEPT2
      ) D
WHERE E.DEPTNO = D.DCODE
CONNECT BY PRIOR E.EMPNO =  E.PEMPNO
START WITH empno = '19966102'
;